### ISSUE TITLE
Pal/Saved/Config/ doesnt exist

### ISSUE THREAD

**Issue by GhostieSpook** [JSamia36/PalWorldServer#1]
Tried to follow every step in the README and it was going fine until the very end. Where the heck is Pal/Saved/Config/ located cause that was never created?

**Comment by JSamia36** [comment]
Hi, it's been awhile since I started a server and believe the process may be different now, compared to early access of the game. I'll try to take a look this week and update it as needed

**Comment by JSamia36** [comment]
Sorry for the delay in getting back, I just ran through the steps again in to try to see. It looks like once you run: 
```
app_update 2394010 validate
``` 
It looks like it doesn't install in the created folder anymore. Instead it should be under 
**/home/{user}/.steam/steam/steamapps/common/PalServer**, if you aren't seeing it here, use 
```
find / -name PalServer
```
(It might also be under /home/{user}/.local/share/Steam/steamapps/common)

The specific config folder will be created once you launch a server for the first time. You will then see the /Config folder appear. It looks like since I wrote this they have added more server commands which can be found [here](https://tech.palworldgame.com/settings-and-operation/arguments). 

Let me know if you have any other questions and I'll try to look into it but hope that solves that issue.
